name: action-jira-linker
on: [pull_request_target]

jobs:
  action-jira-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: exogee-technology/action-jira-linker@v1.0.0
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          jira-user: "taurus.fleming@juristat.com"
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://juristatv2.atlassian.net/
